#!/usr/bin/env sh

[ -z "${REPO_ROOT}" ] && REPO_ROOT="/var/db/kiss"
[ -z "${REPO_MAIN}" ] && REPO_MAIN="$REPO_ROOT/glasnost"
# [ ! -d "${REPO_MAIN}" ] && doas mkdir -p "${REPO_MAIN}"
KERNEL_CONFIG="${REPO_MAIN}/system/linux/files"
[ ! -d "${KERNEL_CONFIG}" ] && doas mkdir -p "${KERNEL_CONFIG}"
doas cp -f ./.config "${KERNEL_CONFIG}/config"
[ ! -d "/root/config" ] && doas mkdir -p /root/config
doas cp -f ./.config $(doas mktemp /root/config/config-$(make kernelversion)-XXXXXXXX)
